name: Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  my-badges:
    name: My Badges
    runs-on: ubuntu-latest
    steps:
      - name: Update Badges
        run: npx update-my-badges ${{github.repository_owner}} --compact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
